# Generated by Django 4.2.16 on 2026-05-15 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('books', '0002_add_book_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, db_column='reserved_at')),
                ('expires_at', models.DateTimeField(db_column='expires_at')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='books.book')),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='members.member')),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
    ]
