# Generated by Django 4.2.16 on 2026-05-15 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=500)),
                ('is_paid', models.BooleanField(db_column='is_paid', default=False)),
                ('is_waived', models.BooleanField(db_column='is_waived', default=False)),
                ('waived_note', models.CharField(blank=True, db_column='waived_note', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='members.member')),
                ('transaction', models.OneToOneField(db_column='transaction_id', on_delete=django.db.models.deletion.PROTECT, related_name='fine', to='transactions.borrowtransaction')),
                ('waived_by', models.ForeignKey(blank=True, db_column='waived_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_fines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fines',
            },
        ),
    ]
