# Generated by Django 4.2.16 on 2026-05-15 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_add_book_fields'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True, db_column='borrowed_at')),
                ('due_date', models.DateTimeField(db_column='due_date')),
                ('returned_at', models.DateTimeField(blank=True, db_column='returned_at', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='members.member')),
            ],
            options={
                'db_table': 'borrow_transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_at', models.DateTimeField(blank=True, db_column='returned_at', null=True)),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.PROTECT, related_name='transaction_items', to='books.book')),
                ('transaction', models.ForeignKey(db_column='transaction_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.borrowtransaction')),
            ],
            options={
                'db_table': 'transaction_items',
            },
        ),
    ]
